### ISSUE TITLE
Embeddings generation

### ISSUE THREAD

**Issue by AsyaOrlova** [GT4SD/gt4sd-core#254] opened 2024-12-05 19:23 UTC
How can I obtain embeddings from the last hidden state of Regression Transformer?

**Comment by jannisborn** [comment] 2024-12-07 09:44
Hi @AsyaOrlova thanks for the interest, that is an interesting one.

Per default this is not supported, however here is a recipe.

```py
from gt4sd.algorithms.conditional_generation.regression_transformer import RegressionTransformer, RegressionTransformerMolecules
from selfies import encoder # This RT works with selfies so we need to convert

# Define your target molecule
smi = "CC(C#C)N(C)C(=O)NC1=CC=C(Cl)C=C1"
target = f"<esol>[MASK][MASK][MASK][MASK][MASK]|{encoder(smi)}"

# Set up model config (standard way)
config = RegressionTransformerMolecules(algorithm_version="solubility", search="greedy")
dummy_model = RegressionTransformer(configuration=config, target=target)
```

That is the standard way, normally would now run the `dummy_model` you would run the model but that only supports sampling molecules with desired properties and runs many forward passes followed by filtering steps, thus there is no way to access the embeddings. In essence you want to run a single forward pass, which happens inside the `generate_batch_regression` [function](https://github.com/GT4SD/gt4sd-core/blob/2398b5b7a8246cb5c3fa3a9a7b608d6febfc8bf5/src/gt4sd/algorithms/conditional_generation/regression_transformer/implementation.py#L409) but that does not save the predictions/embeddings as attribute either. 

```py
model = config.generator.model.model

# Retrieve tokenizer and collator
tokenizer = config.generator.model.tokenizer
collator = config.generator.collator
inputs = collator([tokenizer(target)])

# Run model standalone
result = model(**inputs, output_hidden_states=True)
print(len(result), result.logits.shape)
```


`result.logits` is a tensor of shape `BS x T x VocabSize`, so there you go!
You can also access `result.hidden_states` and `result.mems`, for further details on those variables see the HF docs: https://huggingface.co/docs/transformers/en/model_doc/xlnet

Hope this helps! Closing this as complete but feel free to reopen/comment if needed

**Closed by jannisborn** 2024-12-07 09:44 UTC
Labels: enhancement

**Comment by AsyaOrlova** [comment] 2024-12-11 15:19
Is there a way of obtaining embeddings with the fully trained model?

**Comment by jannisborn** [comment] 2024-12-11 15:20
This is. You can control the checkpoint by selecting the `algorithm_version`

**Comment by AsyaOrlova** [comment] 2024-12-11 15:24
I see now, thank you!

**Comment by AsyaOrlova** [comment] 2024-12-12 11:46
I have one more question. I use "uspto" algorithm version and pass reaction SMILES string to the model. It fails with error:
 
ValueError: The context CC(C#C)N(C)C(=O)NC1=CC=C(Cl)C=C1>>CC(C#C)N(C)C(=O)NC1=CC=C(Cl)C=C1 is not a valid SMILES string.

Am I doing it wrong or there is no way of calculating embeddings for reactions (not just molecules)?

**Comment by jannisborn** [comment] 2024-12-12 12:21
For reaction fingerprints there are surely better methods like RXNFP or DRFP

The reason for the error is that the algorithm is parsing a reaction in a position where it is expecting a molecule

**Comment by AsyaOrlova** [comment] 2024-12-12 12:25
Ok, I see. In the Nature Machine Intelligence paper experiments on predicting reaction yields are provided. That’s why I thought it is possible to use the whole reaction as an input.

**Comment by jannisborn** [comment] 2024-12-12 12:31
You can use whole reactions as input and predict e.g., their yield, yes

**Comment by AsyaOrlova** [comment] 2024-12-12 13:13
I’m sorry, I still do not really get, why reactions embeddings generation is not possible despite the ability to predict yields. Is it due to the RegressionTransformerMolecules config?
